### ISSUE TITLE
iFrame top left buttons

### ISSUE THREAD

**Issue by kaitlyntier** [oneworldmarket/idibu-v3-api#5]
Is it possible to hide the dashboard, candidates, and search buttons?

**Comment by TimParkr** [comment]
Hi @kaitlyntier,

I'm the Product Manager here at idibu - thank you for contacting us re this.

It isn't possible to remove all of those buttons per se, but there are some options available for this area when setting up an individual account:

1.  The dashboard can be disabled from inside the clients idibu V3 account - the ID icon then just acts as a home screen button, which will simply take the user to either the adverts or candidate's tab.
2. The search option can be removed from the client's account - this is done in the back end by the tech team when the account is set up.
3. The candidate's tab cannot be removed as this is core functionality.
4. However, relating to points 1 & 2, the Adverts tab can be set as the default home screen. This means that having posted their advert for the first time, whenever the user subsequently opens the iframe, the adverts tab will open by default.

Can you tell me a little more about the project you are working on and the system you are working on integrating the iframe into? If existing conversations are underway outside of this channel re this then I can keep relevant people on our side up to speed.

**Comment by kaitlyntier** [comment]
Thanks!

**Comment by kaitlyntier** [comment]
Thanks!
